=== lfallo1/SOAP_WS_Demo/xml/schemas/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.bycwebsolutions.org/Patient"
	xmlns:tns="http://www.bycwebsolutions.org/Patient" 
	elementFormDefault="qualified">
	
	<!-- root / base object -->
	<element name="patient" type="tns:Patient" />

	<!-- complex types -->
	<complexType name="Patient">
		<sequence>
			<element name="name" type="tns:String15Chars" />
			<element name="age" type="tns:GreaterThanZeroInclusive" />
			<element name="dob" type="date" />
			<element name="gender" type="tns:Gender" />
			<element name="email" type="tns:EmailList" />
			<element name="phone" type="string" maxOccurs="2" />
			<element name="payment" type="tns:PaymentType" />
		</sequence>
		
		<attribute name="id" type="tns:ID" />
		
	</complexType>
	
	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int" />
			<element name="insurance" type="tns:Insurance" />
		</choice>
	</complexType>
	
	<complexType name="Insurance">
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>
	</complexType>
	
	<!-- Define custom simple types -->
	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>
	
	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15" />
		</restriction>
	</simpleType>
	
	<simpleType name="GreaterThanZeroInclusive">
		<restriction base="int">
			<minInclusive value="0"></minInclusive>
		</restriction>
	</simpleType>
	
	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>
	
	<simpleType name="EmailList">
		<list itemType="tns:Email" />
	</simpleType>
	
	<simpleType name="Email">
		<restriction base="string">
			<pattern value="([a-z0-9][-a-z0-9_\+\.]*[a-z0-9])@([a-z0-9][-a-z0-9\.]*[a-z0-9]\.(arpa|root|aero|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|st|su|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw)|([0-9]{1,3}\.{3}[0-9]{1,3}))"></pattern>
		</restriction>
	</simpleType>
	
</schema>

=== lfallo1/SOAP_WS_Demo/Patient_FallonLance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.bycwebsolutions.org/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bycwebsolutions.org/Patient xsd/Patient.xsd ">
	<tns:id>1</tns:id>
	<tns:name>Lance Fallon</tns:name>
	<tns:age>30</tns:age>
	<tns:dob>1986-10-12</tns:dob>
	<tns:gender>M</tns:gender>
	<tns:email>fallon.lance@gmail.com</tns:email>
	<tns:phone>4108425526</tns:phone>
</tns:patient>

=== lfallo1/SOAP_WS_Demo/xml/data/Patient_FallonLance.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.bycwebsolutions.org/Patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bycwebsolutions.org/Patient ../schemas/Patient.xsd " id="1">
	<tns:name>Lance Fallon</tns:name>
	<tns:age>30</tns:age>
	<tns:dob>1986-10-12</tns:dob>
	<tns:gender>M</tns:gender>
	<tns:email>fallon.lance@gmail.com lance1086@hotmail.com</tns:email>
	<tns:phone>4108425526</tns:phone>
	<tns:payment>
		<tns:insurance>
			<tns:provider>Blue Cross</tns:provider>
			<tns:limit>2000</tns:limit>
		</tns:insurance>
	</tns:payment>
</tns:patient>
